window.EXPO_NEWS = [
  {
    "number": 1,
    "title": "Criadores têm até o dia 30 para garantir espaço gratuito para exposição e comercialização de animais na Expofeira 2026",
    "date": "21/07/2026",
    "source": "Amapá Digital",
    "medium": "Portal",
    "topic": "Agronegócio",
    "author": "Redação",
    "summary": "Divulga o prazo de inscrição e a disponibilidade de vagas gratuitas para bovinos, bubalinos e ovinos.",
    "url": "https://www.amapadigital.com.br/novo/noticia/21/07/2026-criadores-tem-ate-o-dia-30-para-garantir-espaco-gratuito-para-exposicao-e-comercializacao-de-animais-na-expofeira-2026.ghtml",
    "group": "Agro"
  },
  {
    "number": 2,
    "title": "Expofeira 2026: Reunião alinha organização e segurança para o Festival das Aparelhagens",
    "date": "21/07/2026",
    "source": "Jornal O Guarani",
    "medium": "Portal",
    "topic": "Cultura e segurança",
    "author": "Redação",
    "summary": "Apresenta o planejamento de fluxos, infraestrutura e protocolos de segurança do Festival das Aparelhagens.",
    "url": "https://www.jornaloguarani.com/noticia/21%2F07%2F2026-expofeira-2026-reuniao-alinha-organizacao-e-seguranca-para-o-festival-das-aparelhagens.ghtml",
    "group": "Cultura"
  },
  {
    "number": 3,
    "title": "Expofeira 2026 terá estrutura de 312 mil m² de área",
    "date": "21/07/2026",
    "source": "Jornal O Guarani",
    "medium": "Portal",
    "topic": "Infraestrutura",
    "author": "Redação",
    "summary": "Destaca a dimensão da estrutura preparada no Parque de Exposições da Fazendinha.",
    "url": "https://www.jornaloguarani.com/tag?tag=EXPOFEIRA+2026",
    "group": "Infraestrutura e negócios"
  },
  {
    "number": 4,
    "title": "Expofeira 2026: estrutura conta com mais de 500 espaços para empresas expositoras",
    "date": "22/07/2026",
    "source": "Rede Amazônica / Globoplay",
    "medium": "TV",
    "topic": "Infraestrutura e negócios",
    "author": "Jornal do Amapá 1ª Edição",
    "summary": "Reportagem televisiva apresenta a estrutura comercial e os espaços destinados a empresas expositoras.",
    "url": "https://globoplay.globo.com/v/14802234/",
    "group": "Infraestrutura e negócios"
  },
  {
    "number": 5,
    "title": "Prorrogadas inscrições para o concurso Rainha da Expofeira 2026",
    "date": "22/07/2026",
    "source": "Diário do Amapá",
    "medium": "Portal/Jornal",
    "topic": "Cultura",
    "author": "Redação",
    "summary": "Informa a prorrogação das inscrições e a data prevista para a escolha da Rainha da Expofeira.",
    "url": "https://www.diariodoamapa.com.br/cadernos/nota-10/prorrogadas-inscricoes-para-o-concurso-rainha-da-expofeira-2026/",
    "group": "Cultura"
  },
  {
    "number": 6,
    "title": "Governo do Amapá prorroga inscrições para o concurso Rainha da Expofeira 2026",
    "date": "22/07/2026",
    "source": "Jornal O Guarani",
    "medium": "Portal",
    "topic": "Cultura",
    "author": "Flávio Sousa",
    "summary": "Repercussão da prorrogação das inscrições, com informações sobre prazo e realização do concurso.",
    "url": "https://www.jornaloguarani.com/noticia/22%2F07%2F2026-governo-do-amapa-prorroga-inscricoes-para-o-concurso-rainha-da-expofeira-2026.ghtml",
    "group": "Cultura"
  },
  {
    "number": 7,
    "title": "Empresário amapaense prioriza contratação de mão de obra local na montagem da Expofeira 2026",
    "date": "22/07/2026",
    "source": "Jornal O Guarani",
    "medium": "Portal",
    "topic": "Emprego e renda",
    "author": "José Maria",
    "summary": "Ressalta a contratação de mais de 120 trabalhadores locais para montagem da estrutura do evento.",
    "url": "https://www.jornaloguarani.com/noticia/22%2F07%2F2026-empresario-amapaense-prioriza-contratacao-de-mao-de-obra-local-na-montagem-da-expofeira-2026.ghtml",
    "group": "Economia"
  },
  {
    "number": 8,
    "title": "Empresário amapaense prioriza contratação de mão de obra local na montagem da Expofeira 2026",
    "date": "22/07/2026",
    "source": "Amapá Digital",
    "medium": "Portal",
    "topic": "Emprego e renda",
    "author": "José Maria",
    "summary": "Republicação sobre a geração de empregos na fase de montagem do Parque de Exposições.",
    "url": "https://www.amapadigital.com.br/novo/noticia/22/07/2026-empresario-amapaense-prioriza-contratacao-de-mao-de-obra-local-na-montagem-da-expofeira-2026.ghtml",
    "group": "Economia"
  },
  {
    "number": 9,
    "title": "Expofeira 2026 aquece o comércio e impulsiona as vendas antes mesmo da abertura oficial",
    "date": "22/07/2026",
    "source": "Amapá Digital",
    "medium": "Portal",
    "topic": "Economia",
    "author": "Redação",
    "summary": "Mostra o efeito antecipado do evento nas vendas e na expectativa de comerciantes locais.",
    "url": "https://www.amapadigital.com.br/novo/noticia/22/07/2026-expofeira-2026-aquece-o-comercio-e-impulsiona-as-vendas-antes-mesmo-da-abertura-oficial.ghtml",
    "group": "Economia"
  },
  {
    "number": 10,
    "title": "Prodap apresenta planejamento estratégico para atuação na Expofeira 2026",
    "date": "22/07/2026",
    "source": "Prodap",
    "medium": "Órgão oficial",
    "topic": "Tecnologia",
    "author": "João Espíndola",
    "summary": "Detalha o planejamento tecnológico e operacional da Prodap para atendimento durante o evento.",
    "url": "https://www.prodap.ap.gov.br/noticia/23-07-2026-prodap-apresenta-planejamento-estrategico-para-atuacao-na-expofeira-2026",
    "group": "Inovação e tecnologia"
  },
  {
    "number": 11,
    "title": "Expofeira 2026: lei reduz carga de ICMS durante a feira; entenda benefício",
    "date": "23/07/2026",
    "source": "Rede Amazônica / Globoplay",
    "medium": "TV",
    "topic": "Economia e incentivos",
    "author": "Jornal do Amapá 1ª Edição",
    "summary": "Explica o incentivo fiscal destinado a estimular negócios e reduzir custos durante a feira.",
    "url": "https://globoplay.globo.com/v/14805990/",
    "group": "Economia"
  },
  {
    "number": 12,
    "title": "Expofeira 2026 terá espaço dedicado aos setores de petróleo e gás",
    "date": "23/07/2026",
    "source": "Jornal O Guarani",
    "medium": "Portal",
    "topic": "Petróleo e gás",
    "author": "José Maria da Silva",
    "summary": "Anuncia espaço técnico sobre petróleo e gás, com abordagem jurídica, ambiental, social e tecnológica.",
    "url": "https://www.jornaloguarani.com/noticia/23%2F07%2F2026-expofeira-2026-tera-espaco-dedicado-aos-setores-de-petroleo-e-gas-com-profissionais-das-areas-de-engenharia-tecnologia-e-meio-ambiente-para-prestar.ghtml",
    "group": "Inovação e tecnologia"
  },
  {
    "number": 13,
    "title": "Expofeira 2026: Desafio Startup Amapá 2026 vai premiar empresas inovadoras durante o evento",
    "date": "23/07/2026",
    "source": "Jornal O Guarani",
    "medium": "Portal",
    "topic": "Inovação",
    "author": "Redação",
    "summary": "Divulga premiação de R$ 20 mil para startups com soluções de impacto econômico, social, ambiental e tecnológico.",
    "url": "https://www.jornaloguarani.com/noticia/2026-07-23-expofeira-2026-desafio-startup-amap-2026-vai-premiar-empresas-inovadoras-durante-o-evento.ghtml",
    "group": "Inovação e tecnologia"
  },
  {
    "number": 14,
    "title": "Desafio Startup Amapá vai premiar empresas inovadoras durante a Expofeira 2026",
    "date": "23/07/2026",
    "source": "Portal Amapá News",
    "medium": "Portal",
    "topic": "Inovação",
    "author": "Redação",
    "summary": "Repercussão do prêmio promovido pela Fapeap e Setec para fortalecer o ecossistema de inovação.",
    "url": "https://portalamapanews.com.br/desafio-startup-amapa-vai-premiar-empresas-inovadoras-durante-a-expofeira-2026/",
    "group": "Inovação e tecnologia"
  },
  {
    "number": 15,
    "title": "MP-AP e Rede de Proteção definem ações para garantir segurança de crianças e adolescentes na Expofeira 2026",
    "date": "23/07/2026",
    "source": "Folha do Amapá",
    "medium": "Portal",
    "topic": "Direitos humanos e segurança",
    "author": "Dinael Monteiro",
    "summary": "Registra a articulação da rede de proteção e o fluxo integrado de atendimento durante o evento.",
    "url": "https://www.folhadoamapa.com/noticia/101017/mp-ap-e-rede-de-protecao-definem-acoes-para-garantir-seguranca-de-criancas-e-adolescentes-na-expofeira-2026",
    "group": "Segurança"
  },
  {
    "number": 16,
    "title": "Expofeira 2026: vagas abertas para exposição e comercialização de animais",
    "date": "24/07/2026",
    "source": "Rede Amazônica / Globoplay",
    "medium": "TV",
    "topic": "Agronegócio",
    "author": "Jornal do Amapá 1ª Edição",
    "summary": "Reportagem sobre as vagas disponíveis para criadores e comercialização de animais durante a feira.",
    "url": "https://globoplay.globo.com/v/14809522/",
    "group": "Agro"
  },
  {
    "number": 17,
    "title": "Inscrições para exposição de animais na Expofeira 2026 seguem abertas até 30 de julho",
    "date": "24/07/2026",
    "source": "Rede Amazônica / Globoplay",
    "medium": "TV",
    "topic": "Agronegócio",
    "author": "Bom Dia Amazônia - AP",
    "summary": "Reforça o prazo de inscrição e orienta produtores interessados em participar da exposição animal.",
    "url": "https://globoplay.globo.com/v/14807773/",
    "group": "Agro"
  },
  {
    "number": 18,
    "title": "Expofeira 2026 impulsiona economia local e aquece vendas de artigos agropecuários e moda country",
    "date": "24/07/2026",
    "source": "Diário do Amapá",
    "medium": "Portal/Jornal",
    "topic": "Economia",
    "author": "Redação",
    "summary": "Aborda a expectativa de aumento das vendas nos segmentos agropecuário e de moda country.",
    "url": "https://www.diariodoamapa.com.br/cadernos/cidades/expofeira-2026-impulsiona-economia-local-e-aquece-vendas-de-artigos-agropecuarios-e-moda-country/",
    "group": "Agro"
  },
  {
    "number": 19,
    "title": "Prazo para seleção de startups na Expofeira 2026 encerra hoje (27)",
    "date": "27/07/2026",
    "source": "Rede Amazônica / Globoplay",
    "medium": "TV",
    "topic": "Inovação",
    "author": "Bom Dia Amazônia - AP",
    "summary": "Alerta sobre o encerramento das inscrições para startups interessadas em participar do evento.",
    "url": "https://globoplay.globo.com/v/14814252/",
    "group": "Inovação e tecnologia"
  },
  {
    "number": 20,
    "title": "Empreendedores e público da Expofeira 2026 contarão com internet 24 horas",
    "date": "27/07/2026",
    "source": "Diário do Amapá",
    "medium": "Portal/Jornal",
    "topic": "Tecnologia",
    "author": "Redação",
    "summary": "Apresenta o projeto de conectividade 5G e a distribuição de sinal por pavilhões.",
    "url": "https://www.diariodoamapa.com.br/cadernos/cidades/empreendedores-e-publico-da-expofeira-2026-contarao-com-internet-24-horas/",
    "group": "Inovação e tecnologia"
  },
  {
    "number": 21,
    "title": "Empreendedores e público da Expofeira 2026 contarão com internet 24 horas",
    "date": "27/07/2026",
    "source": "Repiquete no Meio do Mundo",
    "medium": "Blog",
    "topic": "Tecnologia",
    "author": "Redação",
    "summary": "Republicação do projeto de conectividade permanente para expositores e visitantes.",
    "url": "https://www.alcilenecavalcante.com.br/economia/empreendedores-e-publico-da-expofeira-2026-contarao-com-internet-24-horas",
    "group": "Inovação e tecnologia"
  },
  {
    "number": 22,
    "title": "Expofeira 2026: Desafio Startup Amapá 2026 vai premiar empresas inovadoras durante o evento",
    "date": "27/07/2026",
    "source": "Blog do Rocha",
    "medium": "Blog",
    "topic": "Inovação",
    "author": "Elton Tavares",
    "summary": "Repercussão do concurso de startups e da premiação para soluções inovadoras.",
    "url": "https://www.blogderocha.com.br/expofeira-2026-desafio-startup-amapa-2026-vai-premiar-empresas-inovadoras-durante-o-evento/",
    "group": "Inovação e tecnologia"
  },
  {
    "number": 23,
    "title": "Lançamento do Liquida Santana fará prévia da Expofeira 2026 com participação de mais de 140 lojistas",
    "date": "27/07/2026",
    "source": "Jornal O Guarani",
    "medium": "Portal",
    "topic": "Comércio",
    "author": "Redação",
    "summary": "Relaciona a campanha comercial de Santana à movimentação econômica que antecede a feira.",
    "url": "https://www.jornaloguarani.com/noticia/27%2F07%2F2026-lancamento-do-liquida-santana-fara-previa-da-expofeira-2026-com-participacao-de-mais-de-140-lojistas.ghtml",
    "group": "Economia"
  },
  {
    "number": 24,
    "title": "Forças de segurança realizam ajustes finais para o plano de trânsito, saúde e segurança da Expofeira 2026",
    "date": "28/07/2026",
    "source": "Amapá Digital",
    "medium": "Portal",
    "topic": "Segurança e mobilidade",
    "author": "Agência de Notícias do Amapá",
    "summary": "Detalha a atuação prevista de mais de 800 agentes nas áreas interna e externa do parque.",
    "url": "https://www.amapadigital.com.br/novo/noticia/28/07/2026-forcas-de-seguranca-realizam-ajustes-finais-para-o-plano-de-transito-saude-e-seguranca-da-expofeira-2026.ghtml",
    "group": "Segurança"
  },
  {
    "number": 25,
    "title": "Expofeira 2026 contará com Arena do Agro, serviços e incentivo à produção rural",
    "date": "28/07/2026",
    "source": "Jornal O Guarani",
    "medium": "Portal",
    "topic": "Agronegócio",
    "author": "Redação",
    "summary": "Apresenta a Arena do Agronegócio, a Vitrine da Agricultura Familiar e o Corredor do Açaí.",
    "url": "https://www.jornaloguarani.com/noticia/28%2F07%2F2026-expofeira-2026-contara-com-arena-do-agro-servicos-e-incentivo-a-producao-rural.ghtml",
    "group": "Agro"
  },
  {
    "number": 26,
    "title": "Lançamento do Liquida Santana na Expofeira 2026",
    "date": "28/07/2026",
    "source": "Jornal O Amapá",
    "medium": "Portal/Jornal",
    "topic": "Comércio",
    "author": "Jorge Cesar",
    "summary": "Repercussão do lançamento da campanha comercial vinculada à Expofeira.",
    "url": "https://jornaloamapa.com/",
    "group": "Economia"
  },
  {
    "number": 27,
    "title": "Expofeira 2026 adota protocolos sanitários para garantir segurança aos animais",
    "date": "29/07/2026",
    "source": "Amapá Digital",
    "medium": "Portal",
    "topic": "Sanidade animal",
    "author": "Jorge César",
    "summary": "Explica a quarentena, o controle de acesso e as exigências sanitárias para o ingresso dos animais.",
    "url": "https://www.amapadigital.com.br/novo/noticia/29/07/2026-expofeira-2026-adota-protocolos-sanitarios-para-garantir-seguranca-aos-animais.ghtml",
    "group": "Agro"
  },
  {
    "number": 28,
    "title": "Expofeira 2026 adota rigoroso protocolo sanitário e quarentena para receber cerca de 600 animais na Fazendinha",
    "date": "29/07/2026",
    "source": "Folha do Amapá",
    "medium": "Portal",
    "topic": "Sanidade animal",
    "author": "Diaelson Monteiro",
    "summary": "Repercussão das medidas de biossegurança e da previsão de recebimento de aproximadamente 600 animais.",
    "url": "https://www.folhadoamapa.com/noticia/101437/expofeira-2026-adota-rigoroso-protocolo-sanitario-e-quarentena-para-receber-cerca-de-600-animais-na-fazendinha",
    "group": "Agro"
  },
  {
    "number": 29,
    "title": "Reunião apresenta regulamento e alinha etapas do concurso Rainha da Expofeira 2026",
    "date": "29/07/2026",
    "source": "Jornal O Guarani",
    "medium": "Portal",
    "topic": "Cultura",
    "author": "Redação",
    "summary": "Informa o alinhamento com candidatas, equipes e organização para a realização da final.",
    "url": "https://www.jornaloguarani.com/noticia/29%2F07%2F2026-reuniao-apresenta-regulamento-e-alinha-etapas-do-concurso-rainha-da-expofeira-2026.ghtml",
    "group": "Cultura"
  },
  {
    "number": 30,
    "title": "Reunião apresenta regulamento e alinha etapas do concurso Rainha da Expofeira 2026",
    "date": "29/07/2026",
    "source": "Amapá Digital",
    "medium": "Portal",
    "topic": "Cultura",
    "author": "Flávio Sousa",
    "summary": "Republicação com informações sobre regulamento, etapas e representatividade das candidatas.",
    "url": "https://www.amapadigital.com.br/novo/noticia/29/07/2026-reuniao-apresenta-regulamento-e-alinha-etapas-do-concurso-rainha-da-expofeira-2026.ghtml",
    "group": "Cultura"
  },
  {
    "number": 31,
    "title": "Arena do Agro será destaque da Expofeira 2026 com serviços e apoio ao produtor rural",
    "date": "29/07/2026",
    "source": "Conecta Amapá",
    "medium": "Portal",
    "topic": "Agronegócio",
    "author": "Redação",
    "summary": "Apresenta serviços, tecnologias e oportunidades para produtores rurais na Arena do Agro.",
    "url": "https://conectamapa.com/category/noticias/cidades/",
    "group": "Agro"
  },
  {
    "number": 32,
    "title": "Expofeira 2026 contará com Arena do Agro, serviços e incentivo à produção rural",
    "date": "29/07/2026",
    "source": "Diário do Amapá",
    "medium": "Portal/Jornal",
    "topic": "Agronegócio",
    "author": "Redação",
    "summary": "Detalha os espaços voltados ao agronegócio, agricultura familiar e cadeia produtiva do açaí.",
    "url": "https://www.diariodoamapa.com.br/cadernos/cidades/expofeira-2026-contara-com-arena-do-agro-servicos-e-incentivo-a-producao-rural/",
    "group": "Agro"
  },
  {
    "number": 33,
    "title": "Espaço de Óleo e Gás reúne gigantes globais com faturamento superior a meio trilhão de reais",
    "date": "05/08/2026",
    "source": "Expofeira 2026",
    "medium": "Material para imprensa",
    "topic": "Petróleo, gás e energia",
    "author": "Comissão de Eventos da Expofeira 2026",
    "summary": "Petrobras, Transpetro, Constellation, OceanPact, Grupo CBO e outras empresas integram o espaço dedicado à cadeia de óleo e gás.",
    "url": "docs/materia-expofeira-oleo-gas.html",
    "group": "Petróleo, gás e energia"
  }
];
